### ISSUE TITLE
"sh: beatags: command not found"  in  ajoke-get-hierarchy.pl 

### ISSUE THREAD

**Issue by eaclarich** [baohaojun/ajoke#15]
I get this when pressing M-g j h in OS X yosemite. I see the problem here is that the "beatags" command is not installed in my system so I figured that might come included in your "beagrep" project. (I had no luck installing it from source)

Anyway, I feel ajoke is just the thing I need to explore a large java codebase I'm working on right now. If you have any ideas/pointers at what I am missing that would be a blessing. Otherwise I will just have to stick with eclim.:-(

Thanks :-)

Detailed error in emacs follows:

-*- mode: compilation; default-directory: "/Xdev/tc2cv/AttributeInheritance.participant/src/attributeinheritance/participant/" -*-
Compilation started at Sun Jul 26 03:22:16

ajoke-get-hierarchy.pl attributeinheritance.participant.AttributeCascade -m EXTENSION_ID
sh: beatags: command not found
No working file for attributeinheritance.participant.AttributeCascade at /Users/eaclarich/.emacs.d/ajoke/bin/ajoke-get-hierarchy.pl line 41.

Compilation exited abnormally with code 1 at Sun Jul 26 03:22:16

**Comment by baohaojun** [comment]
Hi, eaclarich

Thank you for trying ajoke! I thought nobody would actually try it out:-)

And sorry for breaking ajoke. I have just updated the readme, so you can try again, this time check out ajoke using: 

`git clone https://github.com/baohaojun/ajoke -b gnu-global --recursive`

Yes your are right to notice that I have switched ajoke to use beagrep, it will be a lot faster than the GNU Global version, but currently it's still work in progress.
