### ISSUE TITLE
Source jars?

### ISSUE THREAD

**Issue by wcummings** [baohaojun/ajoke#16]
I added "*.jar" to the find command in `mkgtags` because it was spitting out warning about grepping class files. Does ajoke process sources in jars? Is this an OK thing to do?

**Comment by baohaojun** [comment]
Sorry for the late reply. Yes, I made it work with jars. Jar files can extract class/method/field info, which can be used for ajoke completion and class hierarchy display.

Of course, there could be some bugs if you see grep run on jars, it makes no sense.

BTW, I have switched from gtags to beatags, and ajoke now could have been broken, unless you try it with my system-config project together.
